{{- $nm := include "cmak.name" . -}}
{{- $version := get (default (dict "tag" .Chart.Version) .Values.image) "tag" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $nm }}-clusters
  labels:
    {{- include "cmak.labels" . | nindent 4 }}
spec:
  backoffLimit: 4
  ttlSecondsAfterFinished: 180
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: {{ $nm }}-clusters
          configMap:
            name: {{ $nm }}-clusters
      containers:
        - name: setup
          image: "eshepelyuk/cmak-operator-cli:{{ $version }}"
          command: ['python3', './json2zk.py']
          args:
            - '{{ $nm }}.{{ $.Release.Namespace }}:2181'
            - '/kafka-manager/configs'
            - '/opt/clusters'
          volumeMounts:
            - name: {{ $nm }}-clusters
              mountPath: /opt/clusters
