apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: istio-eks
  region: ap-northeast-1

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: appmesh-controller
      namespace: appmesh-system
    attachPolicyARNs:
      - "arn:aws:iam::aws:policy/AWSAppMeshFullAccess"
      - "arn:aws:iam::aws:policy/AWSCloudMapFullAccess"
