---
apiVersion: v1
kind: Namespace
metadata:
  name: prod

---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedNamespace
metadata:
  name: prod
  namespace: prod
spec:
  placement:
    clusters:
    - name: linc-eks-1
    - name: linc-eks-2
